version: '3'

services:
  rang-compose-mysql:
    image: mysql:latest
    container_name: rang-compose-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha-mysql
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - rang-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 30s
      retries: 3

  rang-wildfly:
    image: lcsmachaado/rang-processo-seletivo:latest
    container_name: rang-wildfly
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    depends_on:
      rang-compose-mysql:
        condition: service_healthy
    networks:
      - rang-network

networks:
  rang-network:
    driver: bridge

volumes:
  database:
    driver: local
